# bashrc
export CFLAGS="-O2 -march=i686 -pipe" 
export CXXFLAGS="${CFLAGS}"
export CHOST="i686-pc-linux-gnu"
export MAKEOPTS="-j1"

#ccache
if [ -x /usr/bin/ccache ]; then
    PATH="/usr/lib/ccache/bin/:${PATH}"
    CCACHE_DIR="/var/tmp/ccache"
    SANDBOX_WRITE="${SANDBOX_WRITE}:${CCACHE_DIR}"
fi
